### ISSUE TITLE
Module not install - 

### ISSUE THREAD

**Issue by ramsystematix** [rakeshmagento/magento2-auto-sku-generator#1]
Hello,
I have install your module but getting below error while setup:upgrade,

 [Zend_Db_Adapter_Exception]           
  pdo_mysql extension is not installed

**Comment by rakeshmagento** [comment]
Hi

Which magento2 version you are using ?

**Comment by ramsystematix** [comment]
Hi,
Magento 2.1.5

**Comment by ramsystematix** [comment]
Database table exist for this module?

**Comment by rakeshmagento** [comment]
I would like to check it provide me FTP and SSH site admin details. the
plugin was tested on 2.2.1



Rakesh Jakhar
*Director, Sr. Magento Developer*
E-commerce
Octonism Infotech Pvt. Ltd.
m: +91-94143-49999
a: B 27 Lal Bhadur Nagar, Malviya Nagar, Jaipur
e: rakesh.jakhar1986@gmail.com
<https://www.facebook.com/rakesh.jakhar1987>
<https://www.linkedin.com/in/rakesh-jakhar-49b84b54/>

Magento Certified Developer
<https://www.magentocommerce.com/certification/directory/dev/160417/>

**Comment by ramsystematix** [comment]
Checked on 2.1.9 also, Can I call you, If possible?

**Comment by rakeshmagento** [comment]
ok call me 94143-49999
