### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by michelve** [rakeshmagento/magento2-auto-sku-generator#2]
i followed the instructions and the module is not showing in the admin menu

**Comment by rakeshmagento** [comment]
HI,

Have you applied proper commands after installation of the plugin ?



Rakesh Jakhar
*Director, Sr. Magento Developer*
E-commerce
Octonism Infotech Pvt. Ltd.
m: +91-94143-49999
a: B 27 Lal Bhadur Nagar, Malviya Nagar, Jaipur
e: rakesh.jakhar1986@gmail.com
<https://www.facebook.com/rakesh.jakhar1987>
<https://www.linkedin.com/in/rakesh-jakhar-49b84b54/>

Magento Certified Developer
<https://www.magentocommerce.com/certification/directory/dev/160417/>

**Comment by grassst** [comment]
Hello,

it is also not working for me.
I'm using ver. 2.3.0 (and unfortunately I'm new with magento 2).

Is there also a possibility to get a version working with composer?
I tried to use it in a new installed 2.3 magento.
But there is no /app/code directory, so i created it:

[user@server html]# tree app/code/
app/code/
└── magento2-auto-sku-generator-master
    ├── Rakeshmagento
    │   └── Autosku
    │       ├── etc
    │       │   ├── adminhtml
    │       │   │   ├── di.xml
    │       │   │   └── system.xml
    │       │   ├── config.xml
    │       │   └── module.xml
    │       ├── registration.php
    │       └── Ui
    │           └── DataProvider
    │               └── Product
    │                   └── Form
    │                       └── Modifier
    │                           └── Modifysku.php
    └── README.md

10 directories, 7 files



Thank you for helping me. :-)

Kind regards,
Stefan

**Comment by rakeshmagento** [comment]
The directory structure should be app/code/Rakeshmagento/Autosku.

After copying files to the directory, execute

php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy

**Comment by grassst** [comment]
Perfekt - now it works.

Thank you so much!
