### ISSUE TITLE
Work for a new product but not for child Products

### ISSUE THREAD

**Issue by pmoreno1980** [rakeshmagento/magento2-auto-sku-generator#4]
Thanks for the extension, Work for a new product but not for child Products. If I have a configurable product and I want to create a child doesn't work

**Comment by rakeshmagento** [comment]
thanks for your feedback, the plugin is only for the simple items.


Rakesh Jakhar
*Director, Sr. Magento Developer*
E-commerce
Octonism Infotech Pvt. Ltd.
m: +91-94143-49999
a: B 27 Lal Bhadur Nagar, Malviya Nagar, Jaipur
e: rakesh.jakhar1986@gmail.com
<https://www.facebook.com/rakesh.jakhar1987>
<https://www.linkedin.com/in/rakesh-jakhar-49b84b54/>

Magento Certified Developer
<https://www.magentocommerce.com/certification/directory/dev/160417/>
