### ISSUE TITLE
SKU Length isnt working

### ISSUE THREAD

**Issue by NafeesKhabir** [rakeshmagento/magento2-auto-sku-generator#5]
I've set SKU Length to 4 but SKU is being generated for 13 numbers and not serially but randomly

Magento 2.2.3

**Comment by rakeshmagento** [comment]
The plugins are created for the specific SKU format and specific
requirement.

You can modify it according to your requirement, the file which is
responsible for SKU generation is:-

*app/code/RakeshMagento/Autosku/Ui/DataProvider/Product/Form/Modifier/Modifysku.php*

You can apply your business logic inside a function inside
function _buildSku.


Best Regards,
Rakesh Kumar Jakhar
Magento Certified Developer
<https://u.magento.com/certification/directory/dev/160417/>

**Comment by rakeshmagento** [comment]
Find the attachment for the configuration

<img width="715" alt="Screen Shot 2019-03-25 at 10 01 55 AM" src="https://user-images.githubusercontent.com/3923889/54898404-9cffd500-4ee5-11e9-9b30-569bbd5eb300.png">

After doing the configuration as shown in the screenshot, try to add a new product the SKU will be SKU00, save it. After creating the first product, try to create another one

 now you will see SKU01. 

This is how the plugin is working.

**Comment by NafeesKhabir** [comment]
Im trying to generate string like 102.093.46

where 102 > categoryID
093 > brandID
46 > item number

these ids will be pulled from database except item number. Any suggestion for the f**unction _buildSku**

**Comment by NafeesKhabir** [comment]
My current configuration : 
<img width="1336" alt="Screenshot 2019-03-26 at 11 22 51 AM" src="https://user-images.githubusercontent.com/6972012/54973317-90e54780-4fb9-11e9-8b51-b58488fd340f.png">

How its generating SKU : 
<img width="1345" alt="Screenshot 2019-03-26 at 11 22 20 AM" src="https://user-images.githubusercontent.com/6972012/54973335-a490ae00-4fb9-11e9-8acb-8e81915b0f7f.png">

N.B: I didn't modified any part of your code. But Plugin is not working as expected also it is not following configuration

**Comment by NafeesKhabir** [comment]
You didn't gave solution but closed thread ?

**Comment by rakeshmagento** [comment]
You are looking for different functionality, which needs customization..better to hire a developer.

**Comment by NafeesKhabir** [comment]
Im taking about length its not working.
