### ISSUE TITLE
Auto -01 added

### ISSUE THREAD

**Issue by NafeesKhabir** [rakeshmagento/magento2-auto-sku-generator#6]
If multi person is uploading  product on the site then following thing occurs. 

Suppose three people are uploading different  product at a same time like as below ,

Rakesh Clicks add New product at 10:30
Rakesh Gets SKU : RK001
Rakesh 2 Clicks add New product at 10:31
Rakesh Gets SKU : RK001
Rakesh  3Clicks add New product at 10:32
Rakesh Gets SKU : RK001

Rakesh Clicks save product at 10:34
Rakesh Gets SKU : RK001
Rakesh 2 Clicks save product at 10:35
Rakesh Gets SKU : RK001-1
Rakesh  3 Clicks save product at 10:36
Rakesh Gets SKU : RK001-1-1

**Comment by rakeshmagento** [comment]
If you want it works for multiple admin users you should modify it.
